// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonProcesses.Entities.Context;

#nullable disable

namespace PersonProcesses.Migrations
{
    [DbContext(typeof(PersonProcessesContext))]
    partial class PersonProcessesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonProcesses.Entities.ContactInformation", b =>
                {
                    b.Property<Guid>("UUId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InformationContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InformationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonUUId")
                        .HasColumnType("uuid");

                    b.HasKey("UUId");

                    b.HasIndex("PersonUUId");

                    b.ToTable("ContactInformations");
                });

            modelBuilder.Entity("PersonProcesses.Entities.Person", b =>
                {
                    b.Property<Guid>("UUId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UUId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("PersonProcesses.Entities.ContactInformation", b =>
                {
                    b.HasOne("PersonProcesses.Entities.Person", null)
                        .WithMany("ContactInformations")
                        .HasForeignKey("PersonUUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonProcesses.Entities.Person", b =>
                {
                    b.Navigation("ContactInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
